// Types for BalanceSheetGrowth
export interface BalanceSheetGrowth {
    symbol: string;
    date: string;
    period: string;
    calendarYear: number;
    growthCashAndCashEquivalents: number;
    growthShortTermInvestments: number;
    growthCashAndShortTermInvestments: number;
    growthNetReceivables: number;
    growthInventory: number;
    growthPreferredStock: number;
    growthOtherCurrentAssets: number;
    growthTotalCurrentAssets: number;
    growthPropertyPlantEquipmentNet: number;
    growthGoodwill: number;
    growthIntangibleAssets: number;
    growthGoodwillAndIntangibleAssets: number;
    growthLongTermInvestments: number;
    growthTaxAssets: number;
    growthOtherNonCurrentAssets: number;
    growthTotalNonCurrentAssets: number;
    growthOtherAssets: number | null;
    growthTotalAssets: number;
    growthAccountPayables: number;
    growthShortTermDebt: number;
    growthTaxPayables: number;
    growthCapitalLeaseObligations: number;
    growthDeferredRevenue: number;
    growthOtherCurrentLiabilities: number;
    growthTotalCurrentLiabilities: number;
    growthLongTermDebt: number;
    growthDeferredRevenueNonCurrent: number;
    growthDeferredTaxLiabilitiesNonCurrent: number;
    growthOtherNonCurrentLiabilities: number;
    growthTotalNonCurrentLiabilities: number;
    growthOtherLiabilities: number | null;
    growthTotalLiabilities: number;
    growthCommonStock: number;
    growthRetainedEarnings: number;
    growthAccumulatedOtherComprehensiveIncomeLoss: number;
    growthOthertotalStockholdersEquity: number;
    growthTotalStockholdersEquity: number;
    growthTotalLiabilitiesAndStockholdersEquity: number;
    growthTotalInvestments: number;
    growthTotalDebt: number;
    growthNetDebt: number;
    updatedAt: string;
    createdAt: string;
}